### ISSUE TITLE
Make Package

### ISSUE THREAD

**Issue by mitrerogelio** [mitrerogelio/react-tailwind-template#2]
Research GitHub packages and/or node packages in order to simplify the process for users of the project.

**Comment by mitrerogelio** [comment]
@wesleydamasceno 

What should we name the package in NPM?

Os nomes como `react-tailwind-template` já existem...

**Comment by ghost** [comment]
@mitrerogelio 
que tal, "react-tailwindcss-template"?

**Comment by mitrerogelio** [comment]
Good idea. This is now done.
